version: "3.7"

services:

  app:
      build:
        args:
          user: sammy
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: morellato
      container_name: morellato-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      
      
  nginx:
      image: nginx:1.17-alpine
      container_name: morellato-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
    
  vuejs:
      image: node:18.14.2-alpine3.17    
      tty: true #senza questo va in loop
      container_name: morellato_node
      restart: unless-stopped
      ports:
        - 5173:80
      volumes:
        - ./:/var/www
        
      